services:
  app:
    build: .
    restart: always
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${DB_PORT}/${POSTGRES_DB}
      - BOT_TOKEN=${BOT_TOKEN}
      - NODE_ENV=production
    depends_on:
      - db
    volumes:
      - ./pg_data:/var/lib/postgresql/data # Ensure database persistence if db volume fails (redundant but safe)

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=Europe/Kyiv
      - HOST_chromium_headless=true
    ports:
      - "8191:8191"
    restart: always
    # Optimizations for Raspberry Pi (ARM64) & Chromium
    shm_size: '2gb'
    security_opt:
      - seccomp:unconfined

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./backups/latest.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${DB_PORT:-5432}:5432" # Optional: Expose for local debugging
